# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('nome', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('preco', models.FloatField()),
                ('volume', models.FloatField()),
                ('posicao', models.IntegerField()),
                ('remaining_quantity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='custom', max_length=40)),
                ('gelo', models.BooleanField(default=False)),
                ('preco', models.FloatField(default=0)),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('nome', models.CharField(default='', max_length=40, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=50)),
                ('volume', models.FloatField()),
                ('preco', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('qr_code', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDrink',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.Item')),
                ('drink', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='proporcao', to='administration.Drink')),
            ],
            bases=('administration.item',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.Item')),
            ],
            bases=('administration.item',),
        ),
        migrations.CreateModel(
            name='QuantidadeLitro',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.Item')),
                ('m_litros_atual', models.FloatField()),
            ],
            bases=('administration.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='bebida',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Bebida'),
        ),
        migrations.AddField(
            model_name='compra',
            name='qr_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.QrCode'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='drinks',
            field=models.ManyToManyField(related_name='cardapios', to='administration.Drink'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='administration.Compra'),
        ),
    ]
