# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='preco',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
