# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='bebida',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='porcentagem',
        ),
        migrations.AddField(
            model_name='bebida',
            name='posicao',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='Rack',
        ),
    ]
