# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='remaining_quantity',
            field=models.FloatField(default=0),
        ),
    ]
