# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdrink',
            name='drink',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='proporcao', to='administration.Drink'),
        ),
    ]
