# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='id',
        ),
        migrations.AddField(
            model_name='compra',
            name='gelo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='preco',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drink',
            name='preco',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='nome',
            field=models.CharField(default='Especial', max_length=40),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='nome',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='nome',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code',
            field=models.CharField(max_length=200),
        ),
    ]
