# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_drink_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
