# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20170903_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='nome',
        ),
        migrations.AddField(
            model_name='compra',
            name='nome',
            field=models.CharField(default='custom', max_length=40),
        ),
    ]
