# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20170903_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
