# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20170831_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
