# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20170827_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='quantidade',
            new_name='volume',
        ),
    ]
