# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_compra_data_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
