# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import machine.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('creditos', models.FloatField()),
                ('data_nascimento', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', machine.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('preco', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('bebida', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Bebida')),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeLitro',
            fields=[
                ('quantidadecompra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machine.QuantidadeCompra')),
                ('m_litros', models.FloatField()),
            ],
            bases=('machine.quantidadecompra',),
        ),
        migrations.AddField(
            model_name='quantidadecompra',
            name='bebida',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Bebida'),
        ),
        migrations.AddField(
            model_name='compra',
            name='quantidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.QuantidadeCompra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rack',
            name='quantidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.QuantidadeLitro'),
        ),
    ]
