# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_auto_20170825_0310'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
